#========================================================================
# RAST.py
#========================================================================
# This file contains the definition of all RAST constructs.
# This file is automatically generated by RASTImplGen.py.

class BaseRAST( object ):
  def __init__( s ):
    pass

class BitOr( BaseRAST ):
  def __init__( s ):
    pass

class Assign( BaseRAST ):
  def __init__( s, targets, value ):
    s.targets = targets
    s.value = value

class Module( BaseRAST ):
  def __init__( s, module ):
    s.module = module

class ShiftLeft( BaseRAST ):
  def __init__( s ):
    pass

class BitAnd( BaseRAST ):
  def __init__( s ):
    pass

class Const( BaseRAST ):
  def __init__( s, nbits, value ):
    s.nbits = nbits
    s.value = value

class Attribute( BaseRAST ):
  def __init__( s, value, attr ):
    s.value = value
    s.attr = attr

class Sub( BaseRAST ):
  def __init__( s ):
    pass

class Slice( BaseRAST ):
  def __init__( s, value, lower, upper ):
    s.value = value
    s.lower = lower
    s.upper = upper

class Index( BaseRAST ):
  def __init__( s, value, idx ):
    s.value = value
    s.idx = idx

class Add( BaseRAST ):
  def __init__( s ):
    pass

class BitXor( BaseRAST ):
  def __init__( s ):
    pass

class BinOp( BaseRAST ):
  def __init__( s, left, op, right ):
    s.left = left
    s.op = op
    s.right = right

class CombUpblk( BaseRAST ):
  def __init__( s, body ):
    s.body = body

class ShiftRightLogic( BaseRAST ):
  def __init__( s ):
    pass

#----------------------------------------
# RAST visitor
#----------------------------------------

class RASTNodeVisitor( object ):
  # This visitor uses the same code as the Python AST node visitor
  def visit( self, node, *args ):
      method = 'visit_' + node.__class__.__name__
      visitor = getattr( self, method, self.generic_visit )
      return visitor( node, *args )

  def generic_visit( self, node, *args ):
      for field, value in iter_fields( node ):
          if isinstance( value, list ):
              for item in value:
                  if isinstance( item, AST ):
                      self.visit( item, *args )
          elif isinstance( value, AST ):
              self.visit( value, *args )
