#!/usr/bin/env python
#=========================================================================
# proc-translate [options]
#=========================================================================
# This script imports the RTL processor from ProcRTL.py and
# translate it into SystemVerilog. The generated SystemVerilog file will
# be dumped into the current directory ( if no output directory is
# specified ) or the specified output directory.
#
#  -h --help           Display this message
#
#  --output-dir        Set the output directory of translation
#
# Author : Peitian Pan, Shunning Jiang, Christopher Batten
# Date   : June 19, 2019

# Hack to add project root to python path

import argparse
import os
import sys

# Import the translation pass from verilog backend
from pymtl3.passes.backends.verilog import VerilogTranslationPass

# Hack to add project root to python path
cur_dir = os.path.dirname( os.path.abspath( __file__ ) )
while cur_dir:
  if os.path.exists( cur_dir + os.path.sep + "pytest.ini" ):
    sys.path.insert(0, cur_dir)
    break
  cur_dir = os.path.dirname(cur_dir)

# Import the RTL processor
from examples.ex03_proc.ProcRTL import ProcRTL

#=========================================================================
# Command line processing
#=========================================================================

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print("\n"+f" ERROR: {msg}")
    print("")
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print(line[1:].rstrip("\n"))

def parse_cmdline():
  def valid_dir(string):
    assert not string or (os.path.isdir(string) and os.path.exists(string)), \
      "the given path {} does not exist or is not a directory!".format(string)
    return string
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help", action="store_true" )

  # Additional commane line arguments for the translator

  p.add_argument( "--output-dir", default="", type=valid_dir )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

#=========================================================================
# Main
#=========================================================================

def main():
  opts = parse_cmdline()

  # If output directory was specified, change to that directory

  if opts.output_dir:
    os.chdir( opts.output_dir )

  # Instantiate the processor

  proc = ProcRTL()

  # Tag the processor as to be translated

  proc.set_metadata( VerilogTranslationPass.enable, True )

  # Perform translation

  success = False

  try:
    proc.elaborate()
    proc.apply( VerilogTranslationPass() )
    success = True
  finally:
    if success:
      path = os.getcwd() + \
             f"/{proc.get_metadata(VerilogTranslationPass.translated_filename)}"
      print("\nTranslation finished successfully!")
      print(f"You can find the generated SystemVerilog file at {path}.")
    else:
      print()
      print("\nTranslation failed!")

main()
