#=========================================================================
# BehavioralRTLIR.py
#=========================================================================
"""Provide behavioral RTLIR AST node types.

This file is automatically generated by BehavioralRTLIRImplGen.py.
"""
from __future__ import absolute_import, division, print_function


class BaseBehavioralRTLIR( object ):
  def __ne__( s, other ):
    return not s.__eq__( other )

class CombUpblk( BaseBehavioralRTLIR ):
  def __init__( s, name, body ):
    s.name = name
    s.body = body

  def __eq__( s, other ):
    if type(s) is not type(other) or s.name != other.name:
      return False
    for x, y in zip( s.body, other.body ):
      if x != y:
        return False
    return True

class SeqUpblk( BaseBehavioralRTLIR ):
  def __init__( s, name, body ):
    s.name = name
    s.body = body

  def __eq__( s, other ):
    if type(s) is not type(other) or s.name != other.name:
      return False
    for x, y in zip( s.body, other.body ):
      if x != y:
        return False
    return True

class Assign( BaseBehavioralRTLIR ):
  def __init__( s, target, value ):
    s.target = target
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.target == other.target and s.value == other.value

class AugAssign( BaseBehavioralRTLIR ):
  def __init__( s, target, op, value ):
    s.target = target
    s.op = op
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.target == other.target and s.op == other.op and s.value == other.value

class If( BaseBehavioralRTLIR ):
  def __init__( s, cond, body, orelse ):
    s.cond = cond
    s.body = body
    s.orelse = orelse

  def __eq__( s, other ):
    if type(s) is not type(other) or s.cond != other.cond:
      return False
    for x, y in zip( s.body, other.body ):
      if x != y:
        return False
    for x, y in zip( s.orelse, other.orelse ):
      if x != y:
        return False
    return True

class For( BaseBehavioralRTLIR ):
  def __init__( s, var, start, end, step, body ):
    s.var = var
    s.start = start
    s.end = end
    s.step = step
    s.body = body

  def __eq__( s, other ):
    if type(s) is not type(other) or s.var != other.var or s.start != other.start or s.end != other.end or s.step != other.step:
      return False
    for x, y in zip( s.body, other.body ):
      if x != y:
        return False
    return True

class Number( BaseBehavioralRTLIR ):
  def __init__( s, value ):
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.value == other.value

class Concat( BaseBehavioralRTLIR ):
  def __init__( s, values ):
    s.values = values

  def __eq__( s, other ):
    if type(s) is not type(other):
      return False
    for x, y in zip( s.values, other.values ):
      if x != y:
        return False
    return True

class ZeroExt( BaseBehavioralRTLIR ):
  def __init__( s, nbits, value ):
    s.nbits = nbits
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.nbits == other.nbits and s.value == other.value

class SignExt( BaseBehavioralRTLIR ):
  def __init__( s, nbits, value ):
    s.nbits = nbits
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.nbits == other.nbits and s.value == other.value

class Reduce( BaseBehavioralRTLIR ):
  def __init__( s, op, value ):
    s.op = op
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.op == other.op and s.value == other.value

class SizeCast( BaseBehavioralRTLIR ):
  def __init__( s, nbits, value ):
    s.nbits = nbits
    s.value = value

  def __eq__( s, other ):
    return type(s) is type(other) and s.nbits == other.nbits and s.value == other.value

class StructInst( BaseBehavioralRTLIR ):
  def __init__( s, struct, keywords, kwargs ):
    s.struct = struct
    s.keywords = keywords
    s.kwargs = kwargs

  def __eq__( s, other ):
    if type(s) is not type(other) or s.struct != other.struct:
      return False
    for x, y in zip( s.keywords, other.keywords ):
      if x != y:
        return False
    for x, y in zip( s.kwargs, other.kwargs ):
      if x != y:
        return False
    return True

class IfExp( BaseBehavioralRTLIR ):
  def __init__( s, cond, body, orelse ):
    s.cond = cond
    s.body = body
    s.orelse = orelse

  def __eq__( s, other ):
    return type(s) is type(other) and s.cond == other.cond and s.body == other.body and s.orelse == other.orelse

class UnaryOp( BaseBehavioralRTLIR ):
  def __init__( s, op, operand ):
    s.op = op
    s.operand = operand

  def __eq__( s, other ):
    return type(s) is type(other) and s.op == other.op and s.operand == other.operand

class BoolOp( BaseBehavioralRTLIR ):
  def __init__( s, op, values ):
    s.op = op
    s.values = values

  def __eq__( s, other ):
    if type(s) is not type(other) or s.op != other.op:
      return False
    for x, y in zip( s.values, other.values ):
      if x != y:
        return False
    return True

class BinOp( BaseBehavioralRTLIR ):
  def __init__( s, left, op, right ):
    s.left = left
    s.op = op
    s.right = right

  def __eq__( s, other ):
    return type(s) is type(other) and s.left == other.left and s.op == other.op and s.right == other.right

class Compare( BaseBehavioralRTLIR ):
  def __init__( s, left, op, right ):
    s.left = left
    s.op = op
    s.right = right

  def __eq__( s, other ):
    return type(s) is type(other) and s.left == other.left and s.op == other.op and s.right == other.right

class Attribute( BaseBehavioralRTLIR ):
  def __init__( s, value, attr ):
    s.value = value
    s.attr = attr

  def __eq__( s, other ):
    return type(s) is type(other) and s.value == other.value and s.attr == other.attr

class Index( BaseBehavioralRTLIR ):
  def __init__( s, value, idx ):
    s.value = value
    s.idx = idx

  def __eq__( s, other ):
    return type(s) is type(other) and s.value == other.value and s.idx == other.idx

class Slice( BaseBehavioralRTLIR ):
  def __init__( s, value, lower, upper ):
    s.value = value
    s.lower = lower
    s.upper = upper

  def __eq__( s, other ):
    return type(s) is type(other) and s.value == other.value and s.lower == other.lower and s.upper == other.upper

class Base( BaseBehavioralRTLIR ):
  def __init__( s, base ):
    s.base = base

  def __eq__( s, other ):
    return type(s) is type(other) and s.base == other.base

class LoopVar( BaseBehavioralRTLIR ):
  def __init__( s, name ):
    s.name = name

  def __eq__( s, other ):
    return type(s) is type(other) and s.name == other.name

class FreeVar( BaseBehavioralRTLIR ):
  def __init__( s, name, obj ):
    s.name = name
    s.obj = obj

  def __eq__( s, other ):
    return type(s) is type(other) and s.name == other.name and s.obj == other.obj

class TmpVar( BaseBehavioralRTLIR ):
  def __init__( s, name ):
    s.name = name

  def __eq__( s, other ):
    return type(s) is type(other) and s.name == other.name

class LoopVarDecl( BaseBehavioralRTLIR ):
  def __init__( s, name ):
    s.name = name

  def __eq__( s, other ):
    return type(s) is type(other) and s.name == other.name

class Invert( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Not( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class UAdd( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class USub( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class And( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Or( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Add( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Sub( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Mult( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Div( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Mod( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Pow( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class ShiftLeft( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class ShiftRightLogic( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class BitAnd( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class BitOr( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class BitXor( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Eq( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class NotEq( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Lt( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class LtE( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class Gt( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class GtE( BaseBehavioralRTLIR ):
  def __eq__( s, other ):
    return type(s) is type(other)

class BehavioralRTLIRNodeVisitor( object ):
  # This visitor uses the same code as the Python AST node visitor
  def visit( self, node, *args ):
    method = 'visit_' + node.__class__.__name__
    visitor = getattr( self, method, self.generic_visit )
    return visitor( node, *args )

  def generic_visit( self, node, *args ):
    for field, value in vars(node).iteritems():
      if isinstance( value, list ):
        for item in value:
          if isinstance( item, BaseBehavioralRTLIR ):
            self.visit( item, *args )
      elif isinstance( value, BaseBehavioralRTLIR ):
        self.visit( value, *args )
