from pymtl3.dsl import Component

class TestSrcRTL( Component ):
  def __init__( s, Type, msgs ) -> None: ...
  def construct( s, Type, msgs ) -> None: ...

class TestSinkRTL( Component ):
  def __init__( s, Type, msgs ) -> None: ...
  def construct( s, Type, msgs ) -> None: ...
