#!/usr/bin/env python
#=========================================================================
# isa-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --proc-impl         {fl,cl,rtl}
#  --xcel-impl         {fl,cl,rtl}
#  --input <dataset>   {cksum-xcel-single}
#  --verify            Verify results
#  --trace             Display line tracing
#  --limit             Set max number of cycles, default=100000
#  --stats             Output stats about execution
#
# Author : Shunning Jiang, Christopher Batten
# Date   : June 10, 2019

# Hack to add project root to python path

import argparse
import os
import re
import struct
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + ".pymtl-python-path" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

from ex03_proc.SparseMemoryImage import SparseMemoryImage
from ex03_proc.tinyrv0_encoding import assemble

from ex04_xcel.ubmark.proc_ubmark_checksum_xcel_single import ubmark_cksum_xcel_single

# from ex03_proc.ProcFL import ProcFL
from ex03_proc.ProcCL import ProcCL
from ex03_proc.ProcRTL import ProcRTL

from ex04_xcel.ChecksumXcelFL  import ChecksumXcelFL
from ex04_xcel.ChecksumXcelCL  import ChecksumXcelCL
from ex04_xcel.ChecksumXcelRTL import ChecksumXcelRTL

from pymtl3 import *
from pymtl3.stdlib.test import TestSrcCL, TestSinkCL
from pymtl3.stdlib.cl.MemoryCL import MemoryCL

from ex03_proc.test.harness import TestHarness

#=========================================================================
# Command line processing
#=========================================================================

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print "\n ERROR: %s" % msg
    print ""
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print line[1:].rstrip("\n")

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help", action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--trace", action="store_true"      )
  p.add_argument( "--proc-impl",  default="rtl", choices=["fl", "cl", "rtl"] )
  p.add_argument( "--xcel-impl",  default="rtl", choices=["fl", "cl", "rtl"] )
  p.add_argument( "--input", default="cksum-xcel-single",
                             choices=["cksum-xcel-single", "cksum-xcel-loop"] )
  p.add_argument( "--limit",   default=1000000, type=int )
  p.add_argument( "--stats",   action="store_true"      )
  p.add_argument( "--verify",  action="store_true"    )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

proc_impl_dict = {
  # "fl" : ProcFL,
  "cl" : ProcCL,
  "rtl": ProcRTL,
}
xcel_impl_dict = {
  "fl" : ChecksumXcelFL,
  "cl" : ChecksumXcelCL,
  "rtl": ChecksumXcelRTL,
}

input_dict = {
  "cksum-xcel-single" : ubmark_cksum_xcel_single,
}

#=========================================================================
# Main
#=========================================================================

def main():
  opts = parse_cmdline()

  # Assemble the test program

  mem_image = input_dict[ opts.input ].gen_mem_image()

  #-----------------------------------------------------------------------
  # Setup simulator
  #-----------------------------------------------------------------------

  # Create test harness and elaborate

  model = TestHarness( proc_impl_dict[ opts.proc_impl ],
                       xcel_impl_dict[ opts.xcel_impl ], 0,
                      # src sink memstall memlat
                        0,  0,   0,       1 )

  from pymtl3.passes import SimpleSim
  model.apply( SimpleSim )
  for x in model._sched.schedule:
    if "up_start" in x.__name__:print(x)
    if "up_pulse" in x.__name__: print(x)
    if "upA" in x.__name__: print(x)

  # Load the program into the model

  model.load( mem_image )

  #-----------------------------------------------------------------------
  # Run the simulation
  #-----------------------------------------------------------------------

  count       = 0
  commit_inst = 0

  model.sim_reset()

  limit = 10000

  while not model.done() and count < limit:
    count = count + 1
    commit_inst += int(model.commit_inst)
    if opts.trace:
      print "{:3}: {}".format( count, model.line_trace() )
    model.tick()

  assert count < limit

  if opts.verify:
    print
    passed = input_dict[ opts.input ].verify( model.mem.mem.mem )
    print
    if not passed:
      exit(1)

  # Display stats

  print( "  total_num_cycles      = {}".format( count ) )
  print( "  total_committed_insts = {}".format( commit_inst ) )
  print( "  CPI                   = {:1.2f}".format( count/float(commit_inst) ) )
  print

  exit(0)

main()
