#!/usr/bin/env python
#=========================================================================
# isa-sim [options]
#=========================================================================
#
#  -h --help           Display this message
#
#  --proc-impl         {fl,cl,rtl}
#  --xcel-impl         {fl,cl,rtl}
#  --input <dataset>   {cksum-xcel-single}
#  --verify            Verify results
#  --trace             Display line tracing
#  --limit             Set max number of cycles, default=100000
#  --stats             Output stats about execution
#
# Author : Shunning Jiang, Christopher Batten
# Date   : June 10, 2019

# Hack to add project root to python path

import argparse
import os
import re
import struct
import sys

sim_dir = os.path.dirname( os.path.abspath( __file__ ) )
while sim_dir:
  if os.path.exists( sim_dir + os.path.sep + "pytest.ini" ):
    sys.path.insert(0,sim_dir)
    break
  sim_dir = os.path.dirname(sim_dir)

from examples.ex03_proc.SparseMemoryImage import SparseMemoryImage
from examples.ex03_proc.tinyrv0_encoding import assemble

from examples.ex04_xcel.ubmark.proc_ubmark_checksum_xcel_single import ubmark_cksum_xcel_single

from examples.ex03_proc.ProcFL import ProcFL
from examples.ex03_proc.ProcCL import ProcCL
from examples.ex03_proc.ProcRTL import ProcRTL

from examples.ex04_xcel.ChecksumXcelFL import ChecksumXcelFL
from examples.ex04_xcel.ChecksumXcelCL import ChecksumXcelCL
from examples.ex04_xcel.ChecksumXcelRTL import ChecksumXcelRTL

from pymtl3 import *
from pymtl3.stdlib.test import TestSrcCL, TestSinkCL
from pymtl3.stdlib.cl.MemoryCL import MemoryCL
from pymtl3.stdlib.ifcs import mk_mem_msg

from examples.ex03_proc.test.harness import TestHarness
from examples.ex04_xcel.ProcXcel import ProcXcel

#=========================================================================
# Command line processing
#=========================================================================

class ArgumentParserWithCustomError(argparse.ArgumentParser):
  def error( self, msg = "" ):
    if ( msg ): print "\n ERROR: %s" % msg
    print ""
    file = open( sys.argv[0] )
    for ( lineno, line ) in enumerate( file ):
      if ( line[0] != '#' ): sys.exit(msg != "")
      if ( (lineno == 2) or (lineno >= 4) ): print line[1:].rstrip("\n")

def parse_cmdline():
  p = ArgumentParserWithCustomError( add_help=False )

  # Standard command line arguments

  p.add_argument( "-h", "--help", action="store_true" )

  # Additional commane line arguments for the simulator

  p.add_argument( "--trace", action="store_true"      )
  p.add_argument( "--proc-impl",  default="rtl", choices=["fl", "cl", "rtl"] )
  p.add_argument( "--xcel-impl",  default="rtl", choices=["fl", "cl", "rtl"] )
  p.add_argument( "--input", default="cksum-xcel-single",
                             choices=["cksum-xcel-single", "cksum-xcel-loop"] )
  p.add_argument( "--limit",   default=1000000, type=int )
  p.add_argument( "--stats",   action="store_true"      )
  p.add_argument( "--verify",  action="store_true"    )

  opts = p.parse_args()
  if opts.help: p.error()
  return opts

proc_impl_dict = {
  "fl" : ProcFL,
  "cl" : ProcCL,
  "rtl": ProcRTL,
}
xcel_impl_dict = {
  "fl" : ChecksumXcelFL,
  "cl" : ChecksumXcelCL,
  "rtl": ChecksumXcelRTL,
}

input_dict = {
  "cksum-xcel-single" : ubmark_cksum_xcel_single,
}

class TestHarness(Component):

  #-----------------------------------------------------------------------
  # constructor
  #-----------------------------------------------------------------------

  def construct( s, proc_cls, xcel_cls, dump_vcd,
                 src_delay, sink_delay,
                 mem_stall_prob, mem_latency ):

    s.commit_inst = OutPort( Bits1 )
    req, resp = mk_mem_msg( 8, 32, 32 )

    s.src  = TestSrcCL ( Bits32, [], src_delay, src_delay  )
    s.sink = TestSinkCL( Bits32, [], sink_delay, sink_delay )

    s.dut  = ProcXcel( proc_cls, xcel_cls )

    s.mem  = MemoryCL(2, latency = mem_latency)

    # Processor <-> Proc/Mngr
    s.connect( s.dut.commit_inst, s.commit_inst )

    s.connect( s.src.send, s.dut.mngr2proc )
    s.connect( s.dut.proc2mngr, s.sink.recv )

    # Processor <-> Memory

    s.connect( s.dut.imem,  s.mem.ifc[0] )
    s.connect( s.dut.dmem,  s.mem.ifc[1] )

  #-----------------------------------------------------------------------
  # load
  #-----------------------------------------------------------------------

  def load( self, mem_image ):

    # Iterate over the sections

    sections = mem_image.get_sections()
    for section in sections:

      # For .mngr2proc sections, copy section into mngr2proc src

      if section.name == ".mngr2proc":
        for i in xrange(0,len(section.data),4):
          bits = struct.unpack_from("<I",buffer(section.data,i,4))[0]
          # self.src.src.msgs.append( Bits(32,bits) )
          self.src.msgs.append( Bits(32,bits) )

      # For .proc2mngr sections, copy section into proc2mngr_ref src

      elif section.name == ".proc2mngr":
        for i in xrange(0,len(section.data),4):
          bits = struct.unpack_from("<I",buffer(section.data,i,4))[0]
          # self.sink.sink.msgs.append( Bits(32,bits) )
          self.sink.msgs.append( Bits(32,bits) )

      # For all other sections, simply copy them into the memory

      else:
        self.mem.write_mem( section.addr, section.data )

  #-----------------------------------------------------------------------
  # done
  #-----------------------------------------------------------------------

  def done( s ):
    return s.src.done() and s.sink.done()

  #-----------------------------------------------------------------------
  # line_trace
  #-----------------------------------------------------------------------

  def line_trace( s ):
    return s.src.line_trace()  + " >" + \
           s.dut.line_trace() + \
           s.mem.line_trace()  + " > " + \
           s.sink.line_trace()

#=========================================================================
# Main
#=========================================================================

def main():
  opts = parse_cmdline()

  # Assemble the test program

  mem_image = input_dict[ opts.input ].gen_mem_image()

  #-----------------------------------------------------------------------
  # Setup simulator
  #-----------------------------------------------------------------------

  # Create test harness and elaborate
  print "--- Proc:", opts.proc_impl, "--- Xcel:", opts.xcel_impl, "---"

  model = TestHarness( proc_impl_dict[ opts.proc_impl ],
                       xcel_impl_dict[ opts.xcel_impl ], 0,
                      # src sink memstall memlat
                        3,  4,   0,       1 )

  from pymtl3.passes import DynamicSim
  model.apply( DynamicSim )

  # Load the program into the model

  model.load( mem_image )

  #-----------------------------------------------------------------------
  # Run the simulation
  #-----------------------------------------------------------------------

  count       = 0
  commit_inst = 0

  model.sim_reset()

  limit = 10000

  if opts.trace:
    print "{:3}: {}".format( count, model.line_trace() )

  while not model.done() and count < limit:
    model.tick()
    commit_inst += int(model.commit_inst)
    count = count + 1
    if opts.trace:
      print "{:3}: {}".format( count, model.line_trace() )

  assert count < limit

  if opts.verify:
    print
    passed = input_dict[ opts.input ].verify( model.mem.mem.mem )
    print
    if not passed:
      exit(1)

  # Display stats

  print( "  total_num_cycles      = {}".format( count ) )
  print( "  total_committed_insts = {}".format( commit_inst ) )
  print( "  CPI                   = {:1.2f}".format( count/float(commit_inst) ) )
  print

  exit(0)

main()
